### ISSUE TITLE
Логіка обрахування високостного року має помилку

### ISSUE THREAD

**Issue by Muxamedin** [futinuti/Hillel_home_works#1]
https://github.com/futinuti/Hillel_home_works/blob/67f75fd6bdd65e469cac9263fa2676f9ea5dceea/domashka_4/leap_year_4.py#L10
1900 не є високостним 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/4419752/197919975-53e2ad1d-5e2f-41c2-9fba-c9b7f2b53b15.png">

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/4419752/197919683-98366f87-544c-473c-bef3-47627a0fdcda.png">

https://github.com/futinuti/Hillel_home_works/blob/67f75fd6bdd65e469cac9263fa2676f9ea5dceea/domashka_4/leap_year_4.py#L7
Рік  має бути за умовою:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/4419752/197920136-e353f1c9-09ad-4e0b-8866-982fb7ba9a79.png">

1900 це вже число що є поза  діапазоном

**Comment by futinuti** [comment]
исправил ошибки, можно перездать ?
