### ISSUE TITLE
Цікаво ,  навіщо вам виводити числа з 3ма нулями після коми?

### ISSUE THREAD

**Issue by Muxamedin** [futinuti/Hillel_home_works#3]
https://github.com/futinuti/Hillel_home_works/blob/40a1bf5d2d7e339fca68114d2cd7e7257b0b9190/domashka_9/dz_2.py#L19
<img width="586" alt="image" src="https://user-images.githubusercontent.com/4419752/201543004-5d8ab177-b2f9-4869-b0e7-dff66ef5d669.png">

**Comment by futinuti** [comment]
Сначала генератор делал через random.random  потом считать -проверять неудобно стало поменял на random.randint а в  print не поменял, обидно
