### ISSUE TITLE
Програма не додає числа - якщо введено 2 числа 

### ISSUE THREAD

**Issue by Muxamedin** [futinuti/Hillel_home_works#4]
https://github.com/futinuti/Hillel_home_works/blob/2de7d64e018296c1892ad5c1cbeeac19920a802b/domashka_16/dz_1.py#L12
![image](https://user-images.githubusercontent.com/4419752/209333889-87cf3c7a-72fd-4409-9509-903dfb5bfa33.png)

![image](https://user-images.githubusercontent.com/4419752/209333757-0e6df001-ed15-475b-9f74-39ab7a7e2148.png)
4 + 10 = 410 ????

**Comment by futinuti** [comment]
Чтото не то
